News page
OlgaVysochanska/project-patron4U pull request #33
Opened 2023-05-16 15:19 UTC by 28Rostyk

Зв'язав пагінацію і пошук з бекендом, залишається зробити на мобільному пристрої кнопку загрузити ще.

2023-05-16 16:25 UTC, OlgaVysochanska requested changes
Дивись, логіку треба перенести в компоненти, пейдж має просто рендерити готові компоненти. Напишу тобі ще в тг. І комент тут нижче я написала стосовно списку і елемента списку, один елемент це лішка, а меп має бути в самому списку, там створюєш лі з ключем і передаєш пропси

2023-05-16 16:25 UTC, OlgaVysochanska commented on src/pages/NewsPage/NewsPageListItem/NewsPageListItem.js
> +  return items.map(({ imgUrl, title, text, date, url, id }) => {
мепаєш список в юелі в компоненті ліст, а айтем це просто лішка

2023-05-17 17:39 UTC, 28Rostyk commented
Все поправив!

2023-05-17 18:45 UTC, OlgaVysochanska approved these changes

2023-05-17 18:46 UTC, merged